### ISSUE TITLE
Consider wiremock as http/server resource

### ISSUE THREAD

**Issue by alileza** [tomatool/tomato#58]
**Is your feature request related to a problem? Please describe.**
In a lot of cases integration test that involving external services, are using wiremock. Even though, tomato built in [http/server](https://github.com/tomatool/tomato/blob/master/docs/resources/http-server.md) also able to solve this problem, having support for wiremock integration would makes it easier for people to integrate.

**Describe the solution you'd like**
Implement wiremock client api that implement [http/server interface](https://github.com/tomatool/tomato/blob/master/handler/http/server/server.go#L10), and use it as we're driver for another resource
```yml
    - name: tomato-http-server
      type: http/server
      ready_check: true
      params:
         driver: wiremock
         host: [wiremock_endpoint]
```
