### ISSUE TITLE
Shell resource prefix feature

### ISSUE THREAD

**Issue by alileza** [tomatool/tomato#60]
**Is your feature request related to a problem? Please describe.**
At the moment each time using `shell` resource, you'd need to specify full shell command, for example
```gherkin
Scenario 1: check pod
   Given "bash" execute "kubectl get pods"
```

when most likely we'd use the same command over and over for the scenario (in this case `kubectl`)

**Describe the solution you'd like**
add `prefix` params that automatically prepended to all command executed by the shell resource, like : 
```yaml
resources:
  - name: kubectl
    type: shell
    params:
        prefix: "kubectl"
```

this way, you would use the resource this way instead

```gherkin
Scenario 1: check pod
   Given "kubectl" execute "get pods"
```
